replicaCount: 1

image:
  repository: food/{{ .Chart.Name }}
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env: {}
# Example:
# env:
#   SPRING_PROFILES_ACTIVE: dev

probes:
  readinessPath: /actuator/health/readiness
  livenessPath: /actuator/health/liveness

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
